# Generated by Django 4.2 on 2023-04-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='collection',
        ),
    ]
